// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskTrackr_API.Models;

#nullable disable

namespace TaskTrackr_API.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20241101210920_Migartion10")]
    partial class Migartion10
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.35")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TaskTrackr_API.Models.SendTaskModel", b =>
                {
                    b.Property<Guid>("DocId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DocumentFile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManagerEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DocId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("TaskTrackr_API.Models.UserModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4539868f-91c5-4f09-88f2-ab287facea85"),
                            CreatedAt = new DateTime(2024, 11, 2, 2, 9, 20, 198, DateTimeKind.Local).AddTicks(7613),
                            Email = "admin@gmail.com",
                            FirstName = "",
                            LastName = "",
                            Password = "$2a$11$K3kkO96PQZAkz4KeKg2aQe6ZJrbnts2lm/SDCyf.cIosKqAd3VsjG",
                            Role = "Admin",
                            UpdatedAt = new DateTime(2024, 11, 2, 2, 9, 20, 198, DateTimeKind.Local).AddTicks(7629),
                            UserImage = "",
                            UserName = "Admin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
